#!/usr/bin/env python3
"""Regenerates themes_herdr.go from herdr's own palettes, so the picker's
colours match herdr's themes exactly.

    gh api 'repos/herdrdev/herdr/contents/src/app/state.rs?ref=v0.9.1' \\
        --jq .content | base64 -d > /tmp/state.rs
    python3 scripts/gen-themes.py /tmp/state.rs v0.9.1 > themes_herdr.go
    gofmt -w themes_herdr.go
"""
import re
import sys

# ratatui's named colours as ANSI colour numbers ("" is Reset: the terminal's own).
NAMED = {
    "Reset": "", "Black": "0", "Red": "1", "Green": "2", "Yellow": "3", "Blue": "4",
    "Magenta": "5", "Cyan": "6", "Gray": "7", "DarkGray": "8", "LightRed": "9",
    "LightGreen": "10", "LightYellow": "11", "LightBlue": "12", "LightMagenta": "13",
    "LightCyan": "14", "White": "15",
}
FIELDS = ["accent", "panel_bg", "sidebar_bg", "active_row_bg", "selection_bg", "surface0", "surface1",
          "surface_dim", "overlay0", "overlay1", "text", "subtext0", "mauve", "green", "yellow", "red",
          "blue", "teal", "peach"]


def color(expr):
    rgb = re.fullmatch(r"Color::Rgb\((\d+),\s*(\d+),\s*(\d+)\)", expr)
    if rgb:
        return "#%02x%02x%02x" % tuple(int(n) for n in rgb.groups())
    named = re.fullmatch(r"Color::(\w+)", expr)
    if named and named.group(1) in NAMED:
        return NAMED[named.group(1)]
    raise SystemExit("unrecognised colour: " + expr)


def main():
    source, version = open(sys.argv[1]).read(), sys.argv[2]
    names = dict(re.findall(r'"([a-z-]+)" => Some\(Self::(\w+)\(\)\)', source))
    palettes = {}
    for fn, body in re.findall(r"pub fn (\w+)\(\) -> Self \{\s*Self \{(.*?)\n\s*\}\s*\}", source, re.S):
        fields = dict(re.findall(r"(\w+):\s*(Color::(?:Rgb\([^)]*\)|\w+))", body))
        if set(FIELDS) <= set(fields):
            palettes[fn] = {f: color(fields[f].strip()) for f in FIELDS}
    print("// Code generated by scripts/gen-themes.py from herdr %s src/app/state.rs. DO NOT EDIT." % version)
    print()
    print("package main")
    print()
    print("// herdrPalettes are herdr's built-in themes, by canonical name. A colour is")
    print("// \"#rrggbb\", an ANSI colour number, or \"\" for the terminal's own (Reset).")
    print("var herdrPalettes = map[string]palette{")
    for name, fn in sorted(names.items()):
        if fn not in palettes:
            raise SystemExit("no palette for " + name)
        p = palettes[fn]
        print("\t%s: {" % _q(name))
        for f in FIELDS:
            print("\t\t%s: %s," % (_go(f), _q(p[f])))
        print("\t},")
    print("}")


def _q(s):
    return '"%s"' % s


def _go(field):
    return "".join(part.capitalize() for part in field.split("_")).replace("Bg", "BG")


main()
